// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: strategynode.proto

package strategynode

import (
	_ "github.com/lendloan/lendproto/common"
	_ "github.com/lendloan/lendproto/rescode"
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StrategynodeService service

func NewStrategynodeServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StrategynodeService service

type StrategynodeService interface {
	// 添加共享记录
	Query(ctx context.Context, in *QueryReq, opts ...client.CallOption) (*QueryRes, error)
}

type strategynodeService struct {
	c    client.Client
	name string
}

func NewStrategynodeService(name string, c client.Client) StrategynodeService {
	return &strategynodeService{
		c:    c,
		name: name,
	}
}

func (c *strategynodeService) Query(ctx context.Context, in *QueryReq, opts ...client.CallOption) (*QueryRes, error) {
	req := c.c.NewRequest(c.name, "StrategynodeService.Query", in)
	out := new(QueryRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StrategynodeService service

type StrategynodeServiceHandler interface {
	// 添加共享记录
	Query(context.Context, *QueryReq, *QueryRes) error
}

func RegisterStrategynodeServiceHandler(s server.Server, hdlr StrategynodeServiceHandler, opts ...server.HandlerOption) error {
	type strategynodeService interface {
		Query(ctx context.Context, in *QueryReq, out *QueryRes) error
	}
	type StrategynodeService struct {
		strategynodeService
	}
	h := &strategynodeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&StrategynodeService{h}, opts...))
}

type strategynodeServiceHandler struct {
	StrategynodeServiceHandler
}

func (h *strategynodeServiceHandler) Query(ctx context.Context, in *QueryReq, out *QueryRes) error {
	return h.StrategynodeServiceHandler.Query(ctx, in, out)
}
