// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: lendnode.proto

package lendnode

import (
	_ "github.com/lendloan/lendproto/common"
	_ "github.com/lendloan/lendprotorescode"
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LendnodeService service

func NewLendnodeServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LendnodeService service

type LendnodeService interface {
}

type lendnodeService struct {
	c    client.Client
	name string
}

func NewLendnodeService(name string, c client.Client) LendnodeService {
	return &lendnodeService{
		c:    c,
		name: name,
	}
}

// Server API for LendnodeService service

type LendnodeServiceHandler interface {
}

func RegisterLendnodeServiceHandler(s server.Server, hdlr LendnodeServiceHandler, opts ...server.HandlerOption) error {
	type lendnodeService interface {
	}
	type LendnodeService struct {
		lendnodeService
	}
	h := &lendnodeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&LendnodeService{h}, opts...))
}

type lendnodeServiceHandler struct {
	LendnodeServiceHandler
}
