// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: lognode.proto

package lognode

import (
	common "github.com/lendloan/lendproto/common"
	_ "github.com/lendloan/lendproto/rescode"
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LognodeService service

func NewLognodeServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LognodeService service

type LognodeService interface {
	Log(ctx context.Context, in *LogReq, opts ...client.CallOption) (*common.Response, error)
	CallLog(ctx context.Context, in *CallLogReq, opts ...client.CallOption) (*common.Response, error)
	// 获取日志
	QueryUserLog(ctx context.Context, in *QueryUserLogReq, opts ...client.CallOption) (*QueryUserLogRes, error)
	// 日志数量
	UserLogCount(ctx context.Context, in *UserLogCountReq, opts ...client.CallOption) (*UserLogCountRes, error)
	// 添加反馈
	AddFeedback(ctx context.Context, in *AddFeedbackReq, opts ...client.CallOption) (*AddFeedbackRes, error)
	// 获取反馈
	GetFeedback(ctx context.Context, in *GetFeedbackReq, opts ...client.CallOption) (*GetFeedbackRes, error)
}

type lognodeService struct {
	c    client.Client
	name string
}

func NewLognodeService(name string, c client.Client) LognodeService {
	return &lognodeService{
		c:    c,
		name: name,
	}
}

func (c *lognodeService) Log(ctx context.Context, in *LogReq, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "LognodeService.Log", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lognodeService) CallLog(ctx context.Context, in *CallLogReq, opts ...client.CallOption) (*common.Response, error) {
	req := c.c.NewRequest(c.name, "LognodeService.CallLog", in)
	out := new(common.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lognodeService) QueryUserLog(ctx context.Context, in *QueryUserLogReq, opts ...client.CallOption) (*QueryUserLogRes, error) {
	req := c.c.NewRequest(c.name, "LognodeService.QueryUserLog", in)
	out := new(QueryUserLogRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lognodeService) UserLogCount(ctx context.Context, in *UserLogCountReq, opts ...client.CallOption) (*UserLogCountRes, error) {
	req := c.c.NewRequest(c.name, "LognodeService.UserLogCount", in)
	out := new(UserLogCountRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lognodeService) AddFeedback(ctx context.Context, in *AddFeedbackReq, opts ...client.CallOption) (*AddFeedbackRes, error) {
	req := c.c.NewRequest(c.name, "LognodeService.AddFeedback", in)
	out := new(AddFeedbackRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lognodeService) GetFeedback(ctx context.Context, in *GetFeedbackReq, opts ...client.CallOption) (*GetFeedbackRes, error) {
	req := c.c.NewRequest(c.name, "LognodeService.GetFeedback", in)
	out := new(GetFeedbackRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LognodeService service

type LognodeServiceHandler interface {
	Log(context.Context, *LogReq, *common.Response) error
	CallLog(context.Context, *CallLogReq, *common.Response) error
	// 获取日志
	QueryUserLog(context.Context, *QueryUserLogReq, *QueryUserLogRes) error
	// 日志数量
	UserLogCount(context.Context, *UserLogCountReq, *UserLogCountRes) error
	// 添加反馈
	AddFeedback(context.Context, *AddFeedbackReq, *AddFeedbackRes) error
	// 获取反馈
	GetFeedback(context.Context, *GetFeedbackReq, *GetFeedbackRes) error
}

func RegisterLognodeServiceHandler(s server.Server, hdlr LognodeServiceHandler, opts ...server.HandlerOption) error {
	type lognodeService interface {
		Log(ctx context.Context, in *LogReq, out *common.Response) error
		CallLog(ctx context.Context, in *CallLogReq, out *common.Response) error
		QueryUserLog(ctx context.Context, in *QueryUserLogReq, out *QueryUserLogRes) error
		UserLogCount(ctx context.Context, in *UserLogCountReq, out *UserLogCountRes) error
		AddFeedback(ctx context.Context, in *AddFeedbackReq, out *AddFeedbackRes) error
		GetFeedback(ctx context.Context, in *GetFeedbackReq, out *GetFeedbackRes) error
	}
	type LognodeService struct {
		lognodeService
	}
	h := &lognodeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&LognodeService{h}, opts...))
}

type lognodeServiceHandler struct {
	LognodeServiceHandler
}

func (h *lognodeServiceHandler) Log(ctx context.Context, in *LogReq, out *common.Response) error {
	return h.LognodeServiceHandler.Log(ctx, in, out)
}

func (h *lognodeServiceHandler) CallLog(ctx context.Context, in *CallLogReq, out *common.Response) error {
	return h.LognodeServiceHandler.CallLog(ctx, in, out)
}

func (h *lognodeServiceHandler) QueryUserLog(ctx context.Context, in *QueryUserLogReq, out *QueryUserLogRes) error {
	return h.LognodeServiceHandler.QueryUserLog(ctx, in, out)
}

func (h *lognodeServiceHandler) UserLogCount(ctx context.Context, in *UserLogCountReq, out *UserLogCountRes) error {
	return h.LognodeServiceHandler.UserLogCount(ctx, in, out)
}

func (h *lognodeServiceHandler) AddFeedback(ctx context.Context, in *AddFeedbackReq, out *AddFeedbackRes) error {
	return h.LognodeServiceHandler.AddFeedback(ctx, in, out)
}

func (h *lognodeServiceHandler) GetFeedback(ctx context.Context, in *GetFeedbackReq, out *GetFeedbackRes) error {
	return h.LognodeServiceHandler.GetFeedback(ctx, in, out)
}
